import React from 'react';

export const TERMS_OF_SERVICE_CONTENT = (
    <div className="prose prose-slate max-w-none text-slate-700 leading-relaxed">
        <p><strong>Last Updated:</strong> April 20, 2026</p>

        <p>
            Please read these Terms of Service ("Terms") carefully before using the Declarative application (the "Service") operated by Kyle Wegner ("us", "we", or "our").
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
            By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
        </p>

        <h2>2. Nature of the Service (Disclaimer)</h2>
        <p>
            <strong>The Service is an AI-powered educational and communication tool. It is NOT a substitute for professional medical advice, diagnosis, or treatment.</strong>
        </p>
        <ul>
            <li>The content generated by this Service is for informational and educational purposes only.</li>
            <li>We do not guarantee the accuracy, completeness, or usefulness of any translation or rating provided by the AI.</li>
            <li>Always seek the advice of your physician, psychologist, or other qualified health provider with any questions you may have regarding a medical condition or the care of a neurodivergent individual.</li>
            <li>Reliance on any information provided by this Service is solely at your own risk.</li>
        </ul>

        <h2>3. Donations and Payments</h2>
        <p>
            The Service is provided free of charge. You may choose to support the developer through voluntary donations via Stripe ("Buy Me a Coffee").
        </p>
        <ul>
            <li><strong>Voluntary Support:</strong> Payments made through the "Buy Me a Coffee" feature are voluntary donations to support the ongoing development and hosting costs of the project.</li>
            <li><strong>One-Time and Monthly Options:</strong> Support may be offered as a one-time donation or as a recurring monthly donation processed by Stripe.</li>
            <li><strong>Recurring Renewal:</strong> Monthly support renews automatically each month until you cancel through Stripe.</li>
            <li><strong>Cancellation Timing:</strong> If you cancel a recurring donation, future renewals will stop, but amounts already processed are still considered final.</li>
            <li><strong>No Goods or Services:</strong> A donation does not entitle you to any premium features, goods, services, or special treatment. It is a gift.</li>
            <li><strong>Non-Refundable:</strong> All donations are final and non-refundable.</li>
        </ul>

        <h2>4. User Conduct</h2>
        <p>
            You agree not to use the Service:
        </p>
        <ul>
            <li>In any way that violates any applicable national or international law or regulation.</li>
            <li>To transmit, or procure the sending of, any advertising or promotional material, including any "junk mail", "chain letter," "spam," or any other similar solicitation.</li>
            <li>To attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Service.</li>
        </ul>

        <h2>5. Intellectual Property</h2>
        <p>
            The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of Kyle Wegner and its licensors.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
            In no event shall Kyle Wegner, nor his partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.
        </p>

        <h2>7. Changes</h2>
        <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
        </p>

        <h2>8. Contact Us</h2>
        <p>
            If you have any questions about these Terms, please contact us at: <a href="mailto:declarativeapp@gmail.com" className="text-sky-600 underline">declarativeapp@gmail.com</a>
        </p>
    </div>
);
